[mcp_servers.supabase-dev]
url = "https://mcp.supabase.com/mcp?project_ref=mjkndfhjnipomjjhgsxv"

[mcp_servers.supabase-prod]
url = "https://mcp.supabase.com/mcp?project_ref=zznsqmcewtzlnfoiefkk&read_only=true"
