[nvim.files]
"nvim" = "~/.config/nvim"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"
"tide/rainbow.fish" = "~/.config/fish/functions/tide/configure/configs/rainbow.fish"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
"git/.gitignore_global" = "~/.gitignore_global"

[hypr.files]
"hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"

[kitty.files]
"kitty" = "~/.config/kitty"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[wofi.files]
"arch/wofi" = "~/.config/wofi"

[waybar.files]
"arch/waybar" = "~/.config/waybar"

[sway.files]
"arch/sway" = "~/.config/sway"

[gtklock.files]
"arch/gtklock" = "~/.config/gtklock"

[swaylock.files]
"swaylock/config" = "~/.config/swaylock/config"

[rofi.files]
"rofi/config.rasi" = "~/.config/rofi/config.rasi"
