[nvim.files]
"nvim" = "~/.config/nvim"

[nvim-windows.files]
"nvim" = "~/AppData/local/nvim"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"
"tide/rainbow.fish" = "~/.config/fish/functions/tide/configure/configs/rainbow.fish"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[git.files]
"git/.gitconfig" = "~/.gitconfig"

[hypr.files]
"hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"

[kitty.files]
"kitty" = "~/.config/kitty"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[waybar.files]
"waybar" = "~/.config/waybar"

[swaylock.files]
"swaylock/config" = "~/.config/swaylock/config"

[rofi.files]
"rofi/config.rasi" = "~/.config/rofi/config.rasi"

[qutebrowser.files]
"qutebrowser/config.py" = "~/.config/qutebrowser/config.py"

[mpv.files]
"mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
