[nvim.files]
"nvim" = "~/.config/nvim"

[zsh.files]
"zsh/zshenv" = "~/.zshenv"
"zsh/.zprofile" = "~/.config/zsh/.zprofile"
"zsh/.zshrc" = "~/.config/zsh/.zshrc"
"zsh/aliases.zsh" = "~/.config/zsh/aliases.zsh"
"zsh/.zsh_plugins.txt" = "~/.config/zsh/.zsh_plugins.txt"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
