[nvim.files]
"nvim" = "~/.config/nvim"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"
"tide/rainbow.fish" = "~/.config/fish/functions/tide/configure/configs/rainbow.fish"

[wezterm.files]
"wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
"git/.gitignore_global" = "~/.gitignore_global"
